AppBundle\Entity\ConjuntoV2:
    type: entity
    table: conjunto_v2
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        kitRef:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: kit_ref
        parteId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: parte_id
        kitCount:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: kit_count
    lifecycleCallbacks: {  }
