AppBundle\Entity\Conjunto:
    type: entity
    table: conjunto
    indexes:
        fk_parte_id_idx:
            columns:
                - PARTE_PAR_ID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        parteKitId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PARTE_KIT_ID
        kitCount:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: KIT_COUNT
    manyToOne:
        partePar:
            targetEntity: Parte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PARTE_PAR_ID:
                    referencedColumnName: PAR_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
