AppBundle\Entity\EquivalenciaV2:
    type: entity
    table: equivalencia_v2
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        equivalenciaRef:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: equivalencia_ref
        part1Id:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: part1_id
        part2Id:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: part2_id
    lifecycleCallbacks: {  }
