AppBundle\Entity\Equivalencia:
    type: entity
    table: equivalencia
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        equivalenciaRef:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: EQUIVALENCIA_REF
        equivalenciaDesc:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: EQUIVALENCIA_DESC
    lifecycleCallbacks: {  }
