AppBundle\Entity\Imagen:
    type: entity
    table: imagen
    indexes:
        fk_IMAGENES_PARTE1_idx:
            columns:
                - PARTE_PAR_ID
    uniqueConstraints:
        IMAGEN_FILE_UNIQUE:
            columns:
                - IMG_FILE
    id:
        imgId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: IMG_ID
            generator:
                strategy: IDENTITY
    fields:
        imgUbicacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: IMG_UBICACION
        imgFile:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: IMG_FILE
    manyToOne:
        partePar:
            targetEntity: Parte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PARTE_PAR_ID:
                    referencedColumnName: PAR_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
