AppBundle\Entity\Marca:
    type: entity
    table: marca
    uniqueConstraints:
        MAR_ID_UNIQUE:
            columns:
                - MAR_ID
    id:
        marId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: MAR_ID
            generator:
                strategy: IDENTITY
    fields:
        marNombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: MAR_NOMBRE
        marObservacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: MAR_OBSERVACION
    lifecycleCallbacks: {  }
