AppBundle\Entity\NombreParte:
    type: entity
    table: nombre_parte
    id:
        parNombreId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PAR_NOMBRE_ID
            generator:
                strategy: IDENTITY
    fields:
        parNombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PAR_NOMBRE
        parNombreIngles:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PAR_NOMBRE_INGLES
        parNombreOtros:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: PAR_NOMBRE_OTROS
        parGrupoId:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: PAR_GRUPO_ID
    lifecycleCallbacks: {  }
