AppBundle\Entity\Parte:
    type: entity
    table: parte
    indexes:
        fk_PARTE_FABRICANTE1_idx:
            columns:
                - FABRICANTE_FAB_ID
        fk_PARTE_NOMBRE_idx:
            columns:
                - PAR_NOMBRE_ID
        fk_PARTE_EQ_idx:
            columns:
                - PAR_EQ_ID
    uniqueConstraints:
        PAR_ID_UNIQUE:
            columns:
                - PAR_ID
        PAR_UPC_UNIQUE:
            columns:
                - PAR_UPC
    id:
        parId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PAR_ID
            generator:
                strategy: IDENTITY
    fields:
        parCodigo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'CODIGO INTERNO DEL FABRICANTE'
            column: PAR_CODIGO
        parUpc:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 'CODIGO UPC 12 DIGITOS'
            column: PAR_UPC
        parSku:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: PAR_SKU
        parLargo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'EMPAQUE CM'
            column: PAR_LARGO
        parAncho:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: PAR_ANCHO
        parEspesor:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: PAR_ESPESOR
        parPeso:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: KILOS
            column: PAR_PESO
        parteOrigen:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: PARTE_ORIGEN
        parCaract:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
                comment: 'MEDIADAS, POSICION O UBICACION EN EL VEHICULO'
            column: PAR_CARACT
        parObservacion:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
                comment: 'TIPS, RECOMENDACIONES '
            column: PAR_OBSERVACION
        parAsin:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 'CODIGO EN AMAZON'
            column: PAR_ASIN
        parSubgrupo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 'SUBCATEGORIA DENTRO DE PARTES, SUSPENCION NORMAL REFORZADOS EXTRAREFORZADOS'
            column: PAR_SUBGRUPO
        parKit:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PAR_KIT
    manyToOne:
        parEq:
            targetEntity: Equivalencia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PAR_EQ_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        fabricanteFab:
            targetEntity: Fabricante
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FABRICANTE_FAB_ID:
                    referencedColumnName: FAB_ID
            orphanRemoval: false
        parNombre:
            targetEntity: NombreParte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PAR_NOMBRE_ID:
                    referencedColumnName: PAR_NOMBRE_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
