AppBundle\Entity\SystemRoles:
    type: entity
    table: system_roles
    uniqueConstraints:
        UNIQ_E2F1B55D57698A6A:
            columns:
                - role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    manyToMany:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: role
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
