AppBundle\Entity\VehiculoImagenes:
    type: entity
    table: vehiculo_imagenes
    indexes:
        fk_veh_id_idx:
            columns:
                - VEH_ID
    uniqueConstraints:
        index3:
            columns:
                - VEH_IMG_NOMBRE
                - VEH_ID
    id:
        vehImgId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: VEH_IMG_ID
            generator:
                strategy: IDENTITY
    fields:
        vehImgNombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: VEH_IMG_NOMBRE
        vehImgUrl:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: VEH_IMG_URL
        vehId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: VEH_ID
    lifecycleCallbacks: {  }
