AppBundle\Entity\VehiculoNota:
    type: entity
    table: vehiculo_nota
    indexes:
        fk_vehiculo_nota_idx:
            columns:
                - VEHICULO_VEH_ID
    id:
        vehNotaId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: VEH_NOTA_ID
            generator:
                strategy: IDENTITY
    fields:
        vehNota:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VEH_NOTA
        fechaNota:
            type: date
            nullable: true
            column: FECHA_NOTA
    manyToOne:
        vehiculoVeh:
            targetEntity: Vehiculo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                VEHICULO_VEH_ID:
                    referencedColumnName: VEH_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
