AppBundle\Entity\VehiculoImagen:
    type: entity
    table: vehiculo_imagen
    indexes:
        fk_vehiculo_idx:
            columns:
                - VEH_ID
    uniqueConstraints:
        index3:
            columns:
                - VEH_IMG_NOMBRE
                - VEH_ID
    id:
        vehImgId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: VEH_IMG_ID
            generator:
                strategy: IDENTITY
    fields:
        vehImgNombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: VEH_IMG_NOMBRE
        vehImgUrl:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: VEH_IMG_URL
    manyToOne:
        veh:
            targetEntity: Vehiculo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                VEH_ID:
                    referencedColumnName: VEH_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
