AppBundle\Entity\Vehiculo:
    type: entity
    table: vehiculo
    indexes:
        fk_VEHICULO_MODELO1_idx:
            columns:
                - MODELO_MOD_ID
    uniqueConstraints:
        VEH_ID_UNIQUE:
            columns:
                - VEH_ID
    id:
        vehId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: VEH_ID
            generator:
                strategy: IDENTITY
    fields:
        anioAniId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ANIO_ANI_ID
        vehVin:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: VEH_VIN
        vehFabDesde:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: VEH_FAB_DESDE
        vehFabHasta:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: VEH_FAB_HASTA
        vehVariante:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: VEH_VARIANTE
        vehCilindros:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: VEH_CILINDROS
        vehLitros:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: VEH_LITROS
        vehValvulas:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: VEH_VALVULAS
        vehLevas:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: VEH_LEVAS
        vehVersion:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VEH_VERSION
        vehTipo:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VEH_TIPO
        vehTraccion:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VEH_TRACCION
        vehCaja:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VEH_CAJA
        vehObservacion:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VEH_OBSERVACION
        nota:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: NOTA
    manyToOne:
        modeloMod:
            targetEntity: Modelo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                MODELO_MOD_ID:
                    referencedColumnName: MOD_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
